dhatim/fastexcel

.travis.yml, .travis/toolchains.xml, fastexcel-reader/pom.xml, fastexcel-reader/src/main/java/org/dhatim/fastexcel/reader/Cell.java, fastexcel-reader/src/main/java/org/dhatim/fastexcel/reader/CellType.java, fastexcel-reader/src/main/java/org/dhatim/fastexcel/reader/Row.java, fastexcel-reader/src/main/java/org/dhatim/fastexcel/reader/RowSpliterator.java, fastexcel-reader/src/test/java/org/dhatim/fastexcel/reader/FastExcelReaderTest.java, pom.xml
* Remove date cell type, dates are number with different display format
* Change date type to LocalDateTime
* Use maven toolchains to manage multiple jdk installation
=> Change date handling

fastexcel-writer/pom.xml, fastexcel-writer/src/main/java/org/dhatim/fastexcel/Border.java, fastexcel-writer/src/main/java/org/dhatim/fastexcel/BorderElement.java, fastexcel-writer/src/main/java/org/dhatim/fastexcel/BorderSide.java, fastexcel-writer/src/main/java/org/dhatim/fastexcel/Style.java, fastexcel-writer/src/main/java/org/dhatim/fastexcel/StyleSetter.java, fastexcel-writer/src/main/java/org/dhatim/fastexcel/Worksheet.java, fastexcel-writer/src/test/java/org/dhatim/fastexcel/Correctness.java, pom.xml
=> Implement flexible border styles

fastexcel-writer/src/main/java/org/dhatim/fastexcel/VisibilityState.java, fastexcel-writer/src/main/java/org/dhatim/fastexcel/Workbook.java, fastexcel-writer/src/main/java/org/dhatim/fastexcel/Worksheet.java, fastexcel-writer/src/test/java/org/dhatim/fastexcel/Correctness.java
Hello, I have added this feature to be able to hide sheets.
=> Add functionality to hide sheets

fastexcel-reader/src/main/java/org/dhatim/fastexcel/reader/ReadableWorkbook.java, fastexcel-reader/src/test/java/org/dhatim/fastexcel/reader/MemoryUsageTest.java
Pass in memory `ZipFile` to `OPCPackage.open()`. This way,
only the compressed xlsx contents is loaded into memory.
Originally `OPCPackage.open(InputStream)` loaded whole uncompressed
sheet xml into memory.
=> drastically improve reader memory consumption when using InputStream

README.md, fastexcel-writer/src/main/java/org/dhatim/fastexcel/Worksheet.java
Added functionality to make filtering row
=> Added functionality to make filtering row

fastexcel-writer/src/main/java/org/dhatim/fastexcel/BorderStyle.java, fastexcel-writer/src/main/java/org/dhatim/fastexcel/StyleSetter.java, fastexcel-writer/src/test/java/org/dhatim/fastexcel/PoiCompatibility.java
Introduces BorderStyle enum based on https://msdn.microsoft.com/en-us/library/documentformat.openxml.spreadsheet.borderstylevalues(v=office.14).aspx
=> BorderStyle enum

fastexcel-reader/src/main/java/org/dhatim/fastexcel/reader/Cell.java, fastexcel-reader/src/test/java/org/dhatim/fastexcel/reader/FastExcelReaderTest.java, fastexcel-reader/src/test/java/org/dhatim/fastexcel/reader/HeaderTest.java, fastexcel-reader/src/test/java/org/dhatim/fastexcel/reader/MemoryUsageTest.java, fastexcel-writer/src/main/java/org/dhatim/fastexcel/Alignment.java, fastexcel-writer/src/main/java/org/dhatim/fastexcel/BorderSide.java, fastexcel-writer/src/main/java/org/dhatim/fastexcel/Cell.java, fastexcel-writer/src/main/java/org/dhatim/fastexcel/Comments.java, fastexcel-writer/src/main/java/org/dhatim/fastexcel/Font.java, fastexcel-writer/src/main/java/org/dhatim/fastexcel/Range.java, fastexcel-writer/src/main/java/org/dhatim/fastexcel/StringCache.java, fastexcel-writer/src/main/java/org/dhatim/fastexcel/StyleCache.java, fastexcel-writer/src/main/java/org/dhatim/fastexcel/StyleSetter.java, fastexcel-writer/src/main/java/org/dhatim/fastexcel/TimestampUtil.java, fastexcel-writer/src/main/java/org/dhatim/fastexcel/Workbook.java, fastexcel-writer/src/main/java/org/dhatim/fastexcel/Worksheet.java, fastexcel-writer/src/test/java/org/dhatim/fastexcel/Benchmarks.java, fastexcel-writer/src/test/java/org/dhatim/fastexcel/Correctness.java, fastexcel-writer/src/test/java/org/dhatim/fastexcel/MemoryUsageTest.java, fastexcel-writer/src/test/java/org/dhatim/fastexcel/PoiCompatibility.java
Fixes most of issues reported by Idea's Code Inspection and Code Cleanup
=> Code inspection fixes

fastexcel-writer/src/main/java/org/dhatim/fastexcel/Worksheet.java, fastexcel-writer/src/test/java/org/dhatim/fastexcel/PoiCompatibility.java
=> api to hide grid lines

fastexcel-writer/src/main/java/org/dhatim/fastexcel/Worksheet.java, fastexcel-writer/src/test/java/org/dhatim/fastexcel/Correctness.java, fastexcel-writer/src/test/java/org/dhatim/fastexcel/PoiCompatibility.java
=> api to set view zoom level

fastexcel-writer/src/main/java/org/dhatim/fastexcel/Color.java
More colors familiar by name added to Colors class
=> added more colors

fastexcel-writer/src/main/java/org/dhatim/fastexcel/AlternateShading.java, fastexcel-writer/src/main/java/org/dhatim/fastexcel/Color.java, fastexcel-writer/src/main/java/org/dhatim/fastexcel/Position.java, fastexcel-writer/src/main/java/org/dhatim/fastexcel/Range.java, fastexcel-writer/src/main/java/org/dhatim/fastexcel/Shading.java, fastexcel-writer/src/main/java/org/dhatim/fastexcel/StyleCache.java, fastexcel-writer/src/main/java/org/dhatim/fastexcel/StyleSetter.java, fastexcel-writer/src/main/java/org/dhatim/fastexcel/Workbook.java, fastexcel-writer/src/main/java/org/dhatim/fastexcel/Worksheet.java
I added more new features for setting:
- page orientation (for the print setup, visible in print preview mode)
[ use: ws.pageOrientation("landscape") ]
- top, bottom, header, footer, right, and left page margin
[ use: ws.leftMargin(0.3) ]
- setting header and footer content
[ use: ws.header("page 1 of ?", Position.RIGHT) ]
[ use: ws.footer("Helix", Position.LEFT, "Arial", 10) ]
[ use: ws.footer("sheetname", Position.CENTER, 8) ]
- freeze pane (some rows and columns kept still while scrolling) 
[ use: ws.freezePane(1, 3) to freeze the first column on the left and the top three rows ]
- shading rows (extension of shadeAlternateRows) so that each Nth row is colored
[ instead of shadeAlternateRows(color), simply use: shadeRows(color, eachNRows) ]
Fixed:
- setAutoFilter (the filters were empty …
=> New features and one fix

fastexcel-writer/src/main/java/org/dhatim/fastexcel/Worksheet.java
Added a custom row height function
=> Custom row height functionality

fastexcel-reader/src/main/java/org/dhatim/fastexcel/reader/RowSpliterator.java
=> support empty <v></v> string cell

fastexcel-writer/src/test/java/org/dhatim/fastexcel/PoiCompatibilityTest.java
=> change "=SUM()" to "SUM()" in test and verify formula with POI

fastexcel-reader/src/main/java/org/dhatim/fastexcel/reader/OPCPackage.java
Excel xlsm's `[Content_Types].xml` is a bit different
=> Ability to read Excel xlsm files

fastexcel-writer/src/main/java/org/dhatim/fastexcel/Font.java, fastexcel-writer/src/main/java/org/dhatim/fastexcel/Workbook.java
=> Fixes: mutiple <definedNames> entries when multiple sheets

e2e/pom.xml, fastexcel-reader/pom.xml, pom.xml
=> Upgrade dependencies

fastexcel-reader/pom.xml, pom.xml
=> Get rid of root pom

fastexcel-writer/src/main/java/org/dhatim/fastexcel/Style.java
If the table already has bold+black (same style+same color) and a new bold+black is added, then **only one alignment** is applied, even if they were different.
=> Aligment applying for bold fonts

fastexcel-writer/src/main/java/org/dhatim/fastexcel/Alignment.java, fastexcel-writer/src/main/java/org/dhatim/fastexcel/Border.java, fastexcel-writer/src/main/java/org/dhatim/fastexcel/BorderElement.java, fastexcel-writer/src/main/java/org/dhatim/fastexcel/Fill.java, fastexcel-writer/src/main/java/org/dhatim/fastexcel/Font.java, fastexcel-writer/src/main/java/org/dhatim/fastexcel/StyleSetter.java, fastexcel-writer/src/main/java/org/dhatim/fastexcel/Workbook.java
=> Replace obsolete links

fastexcel-writer/src/main/java/org/dhatim/fastexcel/Worksheet.java
After researching, moving the sheetProtection tag before the mergeCells tag, the error disappeared. I have to say that excel is really a weird thing.Close #199
=> Fix sheet protection problem

fastexcel-writer/src/main/java/org/dhatim/fastexcel/PaperSize.java, fastexcel-writer/src/main/java/org/dhatim/fastexcel/Worksheet.java
=> Fix javadoc

README.md, fastexcel-writer/src/main/java/org/dhatim/fastexcel/Font.java, fastexcel-writer/src/main/java/org/dhatim/fastexcel/StyleCache.java, fastexcel-writer/src/main/java/org/dhatim/fastexcel/Workbook.java, fastexcel-writer/src/test/java/org/dhatim/fastexcel/CorrectnessTest.java
=> Feature set global default font

e2e/pom.xml, fastexcel-writer/src/main/java/org/dhatim/fastexcel/Cell.java, fastexcel-writer/src/main/java/org/dhatim/fastexcel/TimestampUtil.java, fastexcel-writer/src/test/java/org/dhatim/fastexcel/CorrectnessTest.java, fastexcel-writer/src/test/java/org/dhatim/fastexcel/PoiCompatibilityTest.java
Refactor TimestampUtil with reference to the implementation of POI to ensure compatibility and accuracy. 
#257  [The problem of time conversion](https://github.com/dhatim/fastexcel/issues/257#issuecomment-1411812703)
=> Refactor TimestampUtil 

fastexcel-writer/src/main/java/org/dhatim/fastexcel/Worksheet.java, fastexcel-writer/src/test/java/org/dhatim/fastexcel/CorrectnessTest.java
Fix the issue of hiding rows and columns
=> Fix issue #261

fastexcel-writer/src/main/java/org/dhatim/fastexcel/Cell.java, fastexcel-writer/src/main/java/org/dhatim/fastexcel/Worksheet.java, fastexcel-writer/src/test/java/org/dhatim/fastexcel/CorrectnessTest.java, fastexcel-writer/src/test/java/org/dhatim/fastexcel/PoiCompatibilityTest.java
* Add support for inline strings.
* It is useful if you have a lot of distinct strings.
* References
* [officeopenxml.com](http://officeopenxml.com/SScontentOverview.php#:~:text=s%3D%222%22%20t%3D%22-,inlineStr,-%22%3E)
* [learn.microsoft.com](https://learn.microsoft.com/en-us/dotnet/api/documentformat.openxml.spreadsheet.cell?view=openxml-2.8.1#:~:text=t%3D%22-,inlineStr,-%22%3E%20%20%0A%20%20%20%20%3C)
=> Support inline string

README.md
for https://github.com/dhatim/fastexcel/pull/266#issuecomment-1441545760
=> Add a description about inline string

README.md, fastexcel-writer/src/main/java/org/dhatim/fastexcel/Alignment.java, fastexcel-writer/src/main/java/org/dhatim/fastexcel/StyleSetter.java, fastexcel-writer/src/test/java/org/dhatim/fastexcel/CorrectnessTest.java
This PR adds the ability to rotate text by degrees in cell.
closes #277
=> Ability to rotate text

fastexcel-writer/src/main/java/org/dhatim/fastexcel/ListDataValidation.java, fastexcel-writer/src/main/java/org/dhatim/fastexcel/Workbook.java, fastexcel-writer/src/test/java/org/dhatim/fastexcel/PoiCompatibilityTest.java
=> Fix: escape worksheet name

fastexcel-reader/src/main/java/org/dhatim/fastexcel/reader/Row.java, fastexcel-reader/src/test/java/org/dhatim/fastexcel/reader/RowTest.java
=> Fix: compare 0 based index in getCell

fastexcel-writer/src/main/java/org/dhatim/fastexcel/TimestampUtil.java, fastexcel-writer/src/test/java/org/dhatim/fastexcel/CorrectnessTest.java, fastexcel-writer/src/test/java/org/dhatim/fastexcel/PoiCompatibilityTest.java
See https://github.com/dhatim/fastexcel/issues/304
=> Convert ZonedDateTime correctly

README.md
Update the dependency version in the readme to the latest (0.15.6)
=> Update README.md maven dependency versions

fastexcel-writer/src/main/java/org/dhatim/fastexcel/Table.java
Fixes #321
Make TableStyleInfo public so table style can be used.
=> Fix: Make TableStyleInfo public

fastexcel-writer/src/main/java/org/dhatim/fastexcel/CustomDataValidation.java, fastexcel-writer/src/main/java/org/dhatim/fastexcel/Range.java, fastexcel-writer/src/test/java/org/dhatim/fastexcel/CorrectnessTest.java
Added possibility to define a custom data validation for a worksheet. The custom data validation allows to provide a formula which will be checking correctness in a given cell range.
https://learn.microsoft.com/en-us/previous-versions/office/developer/office-2010/cc881341(v%3doffice.14)
=> Added custom data validation

fastexcel-writer/src/main/java/org/dhatim/fastexcel/HyperLink.java, fastexcel-writer/src/main/java/org/dhatim/fastexcel/HyperLinkType.java, fastexcel-writer/src/main/java/org/dhatim/fastexcel/Worksheet.java, fastexcel-writer/src/test/java/org/dhatim/fastexcel/CorrectnessTest.java
Added possibility to define a type of HyperLink. By default HyperLinks will be added as External HyperLinks to support already implemented HyperLink. It's now possible to create an Internal HyperLink by defining HyperLinkType property.
=> Added internal hyperlinks

fastexcel-writer/src/main/java/org/dhatim/fastexcel/Column.java, fastexcel-writer/src/main/java/org/dhatim/fastexcel/ColumnStyleSetter.java, fastexcel-writer/src/main/java/org/dhatim/fastexcel/GenericStyleSetter.java, fastexcel-writer/src/main/java/org/dhatim/fastexcel/StyleSetter.java, fastexcel-writer/src/main/java/org/dhatim/fastexcel/Worksheet.java, fastexcel-writer/src/test/java/org/dhatim/fastexcel/CorrectnessTest.java
Introduced GenericStyleSetter which is extended by StyleSetter(range) and new ColumnStyleSetter.
Column Style property based on https://learn.microsoft.com/en-us/dotnet/api/documentformat.openxml.spreadsheet.column.style?view=openxml-2.8.1#documentformat-openxml-spreadsheet-column-style
Solves issue #344
=> #344 Added possibility to define style for entire column. 

fastexcel-reader/src/main/java/org/dhatim/fastexcel/reader/OPCPackage.java
This PR is trying to address the issue [https://github.com/dhatim/fastexcel/issues/328](https://github.com/dhatim/fastexcel/issues/328).
The OpenXml spec contains some implicit number format codes that is not explicitly saved in the file. This causes the current functionality to be unable to resolve the format for certain number format ids:
[https://learn.microsoft.com/en-us/dotnet/api/documentformat.openxml.spreadsheet.numberingformat?view=openxml-2.8.1](https://learn.microsoft.com/en-us/dotnet/api/documentformat.openxml.spreadsheet.numberingformat?view=openxml-2.8.1)
This means a `styles.xml` file can contain something like this without having `numFmt` elements at all:
```xml
<cellXfs count="4">
<xf numFmtId="22" fontId="0" fillId="0" borderId="0" xfId="0" applyNumberFormat="1"/>
<xf …
```
=> Fix resolving of implicit number format codes

fastexcel-writer/src/main/java/org/dhatim/fastexcel/Worksheet.java, fastexcel-writer/src/test/java/org/dhatim/fastexcel/CorrectnessTest.java
Fixed issue described here https://github.com/dhatim/fastexcel/issues/373 . Column auto adjustment based on text was broken after adding autosizing of entire columns
=> Fixed auto column width adjustment

e2e/pom.xml, fastexcel-reader/pom.xml, fastexcel-reader/src/main/java/module-info.java, fastexcel-writer/pom.xml, fastexcel-writer/src/main/java/module-info.java, pom.xml
See https://github.com/dhatim/fastexcel/issues/388
=> Add full JPMS modules on Java8

README.md, fastexcel-writer/src/main/java/org/dhatim/fastexcel/Worksheet.java, fastexcel-writer/src/test/java/org/dhatim/fastexcel/CorrectnessTest.java
=> Adjust property order to accommodate Microsoft Excel quirks
