dhatim/fastexcel

- fastexcel-reader/src/main/java/org/dhatim/fastexcel/reader/ReadableWorkbook.java
- fastexcel-reader/src/test/java/org/dhatim/fastexcel/reader/MemoryUsageTest.java
Trying to read a big xlsx file causes `OutOfMemoryError`.
The error is thrown if sheet.xml exceeds 4GB. This is reached for example with a
sheet of 500_000 rows by 100 column with numerical values only.
```
java.lang.OutOfMemoryError: Requested array size exceeds VM limit
at java.base/java.util.Arrays.copyOf(Arrays.java:3744)
at java.base/java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:119)
at java.base/java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:94)
at java.base/java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:154)
at org.apache.poi.util.IOUtils.toByteArray(IOUtils.java:154)
at org.apache.poi.util.IOUtils.toByteArray(IOUtils.java:120)
at org.apache.poi.util.IOUtils.toByteArray(IOUtils.java:107)
at …
```
> allow reading of big files without causing `OutOfMemoryError`

- fastexcel-writer/src/main/java/org/dhatim/fastexcel/Workbook.java
- fastexcel-writer/src/main/java/org/dhatim/fastexcel/Worksheet.java
- fastexcel-writer/src/test/java/org/dhatim/fastexcel/MemoryUsageTest.java
Call `flush()` to write all the rows currently in memory to the workbook's output stream.
After calling flush, all the rows created so far become inaccessible.
Included is a test for creating a 500_000x100 cell sheet.
Closes #41.
> `Worksheet.flush()` for writing current rows to `OutputStream`

- fastexcel-reader/src/main/java/org/dhatim/fastexcel/reader/ReadableWorkbook.java
- fastexcel-reader/src/main/java/org/dhatim/fastexcel/reader/SimpleXmlReader.java
Default XmlInputFactory returns r:id value despite using null namespace.
But the moment another Stax implementation like com.fasterxml.woodstox
registers on the classpath, `getAttributeValue(null,id)` may return null.
See [XMLInputFactory.newFactory()](https://docs.oracle.com/javase/8/docs/api/javax/xml/stream/XMLInputFactory.html#newFactory--) javadoc
This lays ground to actually switch fastexcel reader to use woodstox,
which is considerably faster.
Sample woorkbook.xml for reference:
```
<?xml version="1.0" encoding="UTF-8"?>
<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"
xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
<workbookPr date1904="false"/>
<bookViews>
<workbookView activeTab="0"/>
</bookViews>
<sheets>
<sheet …
```
> use proper namespace when reading r:id sheet attribute in workbook.xml

- fastexcel-writer/src/main/java/org/dhatim/fastexcel/Workbook.java
- fastexcel-writer/src/test/java/org/dhatim/fastexcel/Benchmarks.java
I did a comparison of file size and generation time for all possible compression levels
level | size | time
-- | -- | --
0 | 19360975 | 242
1 | 2761559 | 371
2 | 2209736 | 343
3 | 2467095 | 393
4 | 2158858 | 389
5 | 2287434 | 416
6 | 2281720 | 550
7 | 2299445 | 534
8 | 2293590 | 934
-1 | 2281720 | 534
1. The default (-1) is level 6
2. Level 4 gives best size and very good time
3. Level 2 gives best time and very good size
I think it would be good to set the default to 4
> use compression level 4 by default

- fastexcel-writer/pom.xml
- fastexcel-writer/src/main/java/org/dhatim/fastexcel/Workbook.java
- fastexcel-writer/src/test/java/org/apache/poi/openxml4j/util/ZipSecureFileGateway.java
- fastexcel-writer/src/test/java/org/dhatim/fastexcel/MemoryUsageTest.java
Excel requires specific ZIP flag values in .xlsx that
Java's ZIP implementation does not provide when streaming.
Use specific zip implementation tailored specifically to Excel.
More info at: https://github.com/rzymek/opczip
> writer support for xlsx with sheets.xml over 4GB

- fastexcel-writer/src/main/java/org/dhatim/fastexcel/Comments.java
- fastexcel-writer/src/main/java/org/dhatim/fastexcel/Workbook.java
- fastexcel-writer/src/main/java/org/dhatim/fastexcel/Worksheet.java
- fastexcel-writer/src/test/java/org/dhatim/fastexcel/PoiCompatibility.java
fastexcel-writer: Simple, text-only comment support
Usage:
```java
Worksheet ws = wb.newWorksheet("Worksheet 1");
ws.comment(0, 1, "this is a comment <&>");
```
> writer: simple comment support

- fastexcel-writer/pom.xml
Latest opczip includes LibreOffice compatibility: 
https://github.com/rzymek/opczip/commit/d84563b576788f29245d50c1ab3b92fca9af99ea
> use opczip 1.0.2 - LibreOffice compatibility

- fastexcel-reader/src/main/java/org/dhatim/fastexcel/reader/ReadableWorkbook.java
- fastexcel-reader/src/main/java/org/dhatim/fastexcel/reader/RowSpliterator.java
Apache POI ReadOnlySharedStringsTable.class was used in order to decrease number of objects stored in memory and remove formatting information from strings itself. Before the change SharedStringTable was containing XML elements - now it contains only raw strings. For examined files memory footprint was decreased even up to 85%. I was able to commit fix thanks to Lingaro company (https://lingarogroup.com).
> Shared String Table memory footprint optimization.

- fastexcel-reader/src/main/java/org/dhatim/fastexcel/reader/CellAddress.java
- fastexcel-reader/src/test/java/org/dhatim/fastexcel/reader/CellAddressTest.java
Memory usage test time went down from 1:38 to 1:24.
Microbenchmark results:
```
CellAddressBench.CellAddress1_parse   thrpt    6  4408.714 ± 530.906  ops/ms
CellAddressBench.CellAddress2_parse   thrpt    6  7683.455 ± 664.105  ops/ms
CellAddressBench.CellAddress1_format  thrpt    6  4539.635 ± 522.409  ops/ms
CellAddressBench.CellAddress2_format  thrpt    6  5056.850 ± 398.488  ops/ms
```
@Benchmark
public Object CellAddress1_parse() throws IllegalStateException {
return new Object[]{
new CellAddress("A1"),
new CellAddress("XY1321"),
new CellAddress("$XY1321"),
new CellAddress("XFD1048576")
};
}
@Benchmark
public Object CellAddress1_format() throws IllegalStateException {
return new Object[]{
new CellAddress(0, 0).toString(),
new CellAddress(100, 100).toString(),
new CellAddress(21333, …
> CellAddress performance improvements.

- fastexcel-writer/src/main/java/org/dhatim/fastexcel/Worksheet.java
Just added a valid separator between fontsize and header/footer content to prevent this from happening.
> Fix: when writing timestamp to header or footer (mixing fontSize with timestamp) - invalid format

- fastexcel-writer/src/main/java/org/dhatim/fastexcel/Cell.java
- fastexcel-writer/src/main/java/org/dhatim/fastexcel/Worksheet.java
- fastexcel-writer/src/test/java/org/dhatim/fastexcel/CorrectnessTest.java
- fastexcel-writer/src/test/java/org/dhatim/fastexcel/WriterTest.java
Instead of the runtime checked `value(int, int, Object)` method provide explicitly typed overloads for all the supported types.
> Explicit types on set value

- fastexcel-reader/src/main/java/org/dhatim/fastexcel/reader/OPCPackage.java
- fastexcel-reader/src/main/java/org/dhatim/fastexcel/reader/ReadableWorkbook.java
A workbook may contain only inline strings or no string at all. Excel always adds a "sharedStrings.xml" file but there are known cases where this file is absent: for example, Alteryx (https://community.alteryx.com/t5/Alteryx-Designer-Discussions/Excel-Output-Not-In-Standard-Excel-Format/td-p/316986).
> Handle case where workbook does not contain shared strings

- fastexcel-writer/src/main/java/org/dhatim/fastexcel/Workbook.java
With Java > 8, excessive precision (up to nanoseconds) prevents Excel from reading the generated xlsx. Also, timezone was not accounted for.
> Fix: wrong timestamp in docProps/core.xml

- e2e/pom.xml
- e2e/src/test/java/org.dhatim.fastexcel.benchmarks/ReaderBenchmark.java
Thanks for maintaining this great project. I'm a POI PMC member and maintainer of a fork of monitorjbl's excel-streaming-reader.
I updated your benchmark for POI reading with streaming. The test was set to read in styles which is not needed for the test as it is written. Styles are only needed if you want to use POI DataFormatter to format the data. It has a material effect on the test to read that unnecessary data.
I commented out the monitorjbl test because it crashes with the POI version that is loaded. It can be re-enabled if the POI version is forced to version 4 (eg 4.1.2).
I plan on testing my [fork](https://github.com/pjfanning/excel-streaming-reader) of monitorjbl. I'm adding some extra tuning features to it (eg to optionally not load styles). It will probably not match fastexcel …
> update poi read streaming benchmark

- fastexcel-writer/src/main/java/org/dhatim/fastexcel/Worksheet.java
- fastexcel-writer/src/test/java/org/dhatim/fastexcel/CorrectnessTest.java
Optimize the method of judging whether a cell is in any merged range. According to the test case based on #185, it can save about half of the time. Close #185 .
> Feature optimize merge function

- .github/workflows/build.yml
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> Fix github actions

- fastexcel-writer/src/main/java/org/dhatim/fastexcel/TimestampUtil.java
- fastexcel-writer/src/test/java/org/dhatim/fastexcel/CorrectnessTest.java
This PR fixes the issue when we set the year 1900 for Cells with date value.
E.g. For Date (DD-MM-YYYY), 01-01-1900, the date will be saved as 02-01-1900.
> issue#140 Off by 1 error for dates with year 1900

- .github/workflows/build.yml
- .github/workflows/release.yml
- fastexcel-writer/pom.xml
- fastexcel-writer/src/main/java/org/dhatim/fastexcel/MarginalInformation.java
- fastexcel-writer/src/main/java/org/dhatim/fastexcel/Worksheet.java
- fastexcel-writer/src/main/java/org/dhatim/fastexcel/Writer.java
- fastexcel-writer/src/main/java/org/dhatim/fastexcel/XmlEscapeHelper.java
- fastexcel-writer/src/test/java/org/dhatim/fastexcel/MarginalInformationTest.java
- fastexcel-writer/src/test/java/org/dhatim/fastexcel/XmlEscapeHelperTest.java
Closes #302
- Extract XML escaping logic from `Worksheet.java` to own helper class. This allows easier reuse, better testing, and reduces the complexity of `Worksheet.java`
- Create new Class `MarginalInformation` which represents the header and footer. This reduces duplicated code and makes testing easier.
- Escape header and footer text, this closes #302 
Thank you for reviewing and I hope you consider merging this PR.
Br
Jonas
> Refactor: Use own model for header and footer, improve XML escaping

- fastexcel-reader/src/main/java/org/dhatim/fastexcel/reader/ReadableWorkbook.java
- fastexcel-reader/src/test/java/org/dhatim/fastexcel/reader/Resources.java
- fastexcel-reader/src/test/java/org/dhatim/fastexcel/reader/WithFormatTest.java
Makes `ReadableWorkbook(File inputFile, ReadingOptions readingOptions)` work like `public ReadableWorkbook(InputStream inputStream, ReadingOptions readingOptions)` regarding readingOptions.
> Fix withCellFormat being ignored by file based ReadableWorkbook CTOR

- e2e/src/test/java/org/dhatim/fastexcel/EncryptionTest.java
With the release of POI5.2.4, this problem has been solved and some code wrapping is no longer necessary. https://bz.apache.org/bugzilla/show_bug.cgi?id=66436
```java
// This code does not have to be executed in POI 5.2.4
OPCPackage open = OPCPackage.open(dataStream);
open.save(bos);
byte[] bytes = bos.toByteArray();
fworkbook = new ReadableWorkbook(new ByteArrayInputStream(bytes));
```
> Update encrypt test

- fastexcel-reader/src/main/java/org/dhatim/fastexcel/reader/ReadableWorkbook.java
- fastexcel-reader/src/main/java/org/dhatim/fastexcel/reader/Sheet.java
- fastexcel-reader/src/test/java/org/dhatim/fastexcel/reader/FastExcelReaderTest.java
**Issue:**
`r.getAttribute("http://schemas.openxmlformats.org/officeDocument/2006/relationships", "id")` returns an id that might change if the sheets are rearranged in the workbook. When working with Excel-files from code, we often want to rely on a sheet's id to remain stable regardless of user input.
**Proposed fix:**
Add another field `stableId` to the `Sheet` class, and populate the value using `SimpleXmlReader/getAttribute("sheetId")`. This id will not change even if the order of sheets are changed.  New sheets created will not get conflicting ids either.
> Provide access to the sheet's stable id

- README.md
- fastexcel-writer/src/main/java/org/dhatim/fastexcel/Worksheet.java
- fastexcel-writer/src/test/java/org/dhatim/fastexcel/CorrectnessTest.java
> Right to left Worksheet

- fastexcel-writer/src/main/java/org/dhatim/fastexcel/MarginalInformation.java
- fastexcel-writer/src/main/java/org/dhatim/fastexcel/Properties.java
- fastexcel-writer/src/main/java/org/dhatim/fastexcel/Workbook.java
- fastexcel-writer/src/main/java/org/dhatim/fastexcel/Writer.java
- fastexcel-writer/src/main/java/org/dhatim/fastexcel/XmlEscapeHelper.java
- fastexcel-writer/src/test/java/org/dhatim/fastexcel/CorrectnessTest.java
- fastexcel-writer/src/test/java/org/dhatim/fastexcel/XmlEscapeHelperTest.java
Recently I discovered that the values of properties in the code were not escaped, causing an error when the generated file was opened in Excel.This PR will fix it.
```java
try (OutputStream os = ..., Workbook wb = new Workbook(os, "MyApplication", "1.0");) {
wb.properties()
.setTitle("title property<=")
.setTextProperty("Test TextA", "Lucy<=")
.setHyperlinkBase("https://github.com/search?q=repo%3Adhatim%2Ffastexcel%20fastexcel&type=code");
}
```
> Fixed custom properties not escaping correctly

- fastexcel-writer/src/main/java/org/dhatim/fastexcel/Worksheet.java
- fastexcel-writer/src/test/java/org/dhatim/fastexcel/PoiCompatibilityTest.java
Add support for changing the location of the summary rows / columns for merged rows / columns. This is set on a worksheet level using two flags (summaryBelow and summaryRight) on an outlinePr element inside the sheetPr.
The PoiCompatibilityTest is also updated to validate the default value as well as checking that changing it in FastExcel results in a changed location as read by POI.
> Add support for summary cols above / to the left

- fastexcel-writer/src/main/java/org/dhatim/fastexcel/ListFormulaDataValidation.java
- fastexcel-writer/src/main/java/org/dhatim/fastexcel/Range.java
- fastexcel-writer/src/main/java/org/dhatim/fastexcel/Workbook.java
- fastexcel-writer/src/test/java/org/dhatim/fastexcel/PoiCompatibilityTest.java
Fixing the [issue 453:](https://github.com/dhatim/fastexcel/issues/453): a new data validation is added: `ListFormulaDataValidation`.
This `DataValidation` allow to create a data validation with `list` type and with a `formula` value (to referrer a list, for example with `INDIRECT` formula).
In addition, it is possibility to set global visibility to a range when a named range is added.
> #453: Add new data validation: ListFormulaDataValidation.

- fastexcel-writer/src/main/java/org/dhatim/fastexcel/StringCache.java
- fastexcel-writer/src/test/java/org/dhatim/fastexcel/CorrectnessTest.java
Perserve white spaces by default.
The user just needs to trim the strings themselves in case they don´t want it.
Fixes #450
> Preserve white spaces

- README.md
The build status badge in the repos README reports the status of the latest build, regardless of the branch the build was running against.
This PR suggests to limit the badge to the main branch `master`.
If it was intentional to report any build status in the README, just close the PR w/o comment.
> Suggestion: Adjust build status badge to report master only

- fastexcel-reader/src/main/java/org/dhatim/fastexcel/reader/ReadableWorkbook.java
```java
<workbookPr date1904="1" />
```
fix issue #521 date1904  option does not applies when date1904 attr has val "1" instead of "true"
> fix: [#521] date1904 not applies when xml attr has val "1" instead of "true"
